<MyGrid>:
    name: a
    email: b
        
    GridLayout:
        cols:1
        size:root.width-300, root.height-300
        pos:200,200
        GridLayout:
            cols:2
            Label:
                text:"Name: "
            TextInput:
                id:a
                multiline:False
            Label:
                text:"Email: "
            TextInput:
                id:b
                multiline:False
        Button:
            text:"Submit"